### ISSUE TITLE
建议：支持自定义HttpHeader

### ISSUE THREAD

**Issue by xiaosongmao123** [winsoft666/teemo#10]
1在下载时，应该支持传入自定义httpheader
有的下载链接，需要特定UserAgent，有的需要检查Cookie，有的有referrer防盗链
所以应该支持传入自定义的header。

EntryHandler::requestFileInfo
Slice::start

**Comment by winsoft666** [comment]
Good idea!

**Comment by winsoft666** [comment]
Fixed.
