### ISSUE TITLE
建议：关于Slice低速自动取消下载

### ISSUE THREAD

**Issue by xiaosongmao123** [winsoft666/teemo#12]
现在已经支持设置最大下载速度了（setMaxDownloadSpeed），

但有时网络并不好（中美）
所以希望调整  slice.cpp  ::  start  ::  CURLOPT_LOW_SPEED_LIMIT  处  支持设置最低下载速度和超时时间，

1.用户手动设置后，这样遇到某些分片因为网络原因，可以及时的自动取消下载，而不是一直低速等待
2.用户不设置，那就一直低速等待

PS：我实际遇到的问题是，有的时候，下载很慢，此时暂停，然后立即重新开始下载，速度就很快了。所以需要低速自动中断，然后我会立即调用重新下载，这样下载速度就恢复了。跟网络有关，跟服务器链接策略有关（有的服务器对连接时间过长的链接会调低优先级限速，资源倾斜给新连接上来的链接）

**Comment by winsoft666** [comment]
Fixed!
see `setMinDownloadSpeed`
