### ISSUE TITLE
建议：Slice失败自动重试

### ISSUE THREAD

**Issue by xiaosongmao123** [winsoft666/teemo#13]
我简单看了一下，现在的分片下载逻辑是，

1. 创建slice时， status_(UNFETCH)
2. SliceManager里循环抓到一个UNFETCH的slice执行下载
3. slice::start时标记为DOWNLOADING

4. 当一个slice下载成功或失败后，就不管他了，继续抓下一个UNFETCH的slice，等最后全部分片处理完，检查文件是否下载成功。

所以slice的下载，本身没有出错重试机制

我在下载mp4文件时，按分片下载，下载了一段时间后，使用一些播放器去播放.teemo 文件，实现边下边播

现在遇到某一个slice下载失败，就无法继续播放了。所以希望slice下载失败后，可以立即重新尝试继续下载（比如重试3次），实在没办法了再继续下载下一个分片

另外从逻辑上，
1. 直接重新下载这个出错的分片，可能会下载成功，那么继续下载剩余分片，最终这个文件就显示下载成功了
2. 没有重试机制，那么继续下载剩余分片，最终这个文件就显示下载失败（至少有一个slice出错了）

所以不论是从边下边播的需求，还是从正常下载的需求上看，都需要分片出错自动重试机制

**Comment by winsoft666** [comment]
Fixed.
