### ISSUE TITLE
疑问：关于slice的清理curl_multi_remove_handle

### ISSUE THREAD

**Issue by xiaosongmao123** [winsoft666/teemo#14]
看的不是太仔细，没找到清理，所以问一下

1. 创建了一堆slice
2. slice::start 把这个slice的curl_添加到multi下载curl_multi_add_handle
3. 当fetchUsefulSlice时，检测到已下载成功的，就slice::stop 从multi移除+清理 curl_multi_remove_handle + curl_easy_cleanup

#### 问1. _asyncTaskProcess里multi_
EntryHandler::_asyncTaskProcess()   217行  multi_ = curl_multi_init();

multi_最后没有调用curl_multi_cleanup进行清理？

#### 问2.slice里curl_
slice::stop确实清理了curl_
但是，只有判断下载成功的slice才触发stop().那么那些下载失败的slice里面的curl_，没有清理（curl_multi_remove_handle+curl_easy_cleanup）？

帮我捋一下，告诉我问1和问2是怎么清理的

**Comment by xiaosongmao123** [comment]
我是感觉应该在
entry_handler.cpp::389 行 OutputVerbose(options_->verbose_functor, "[teemo] Downloading end.\n");
下面，

1. 遍历所有slice，检查curl_！=nullptr的，清理一遍curl_multi_remove_handle+curl_easy_cleanup
2. curl_multi_cleanup（multi_）

**Comment by winsoft666** [comment]
实际上是BUG，目前已经修复。
