### ISSUE TITLE
vcpkg CONTROL file has incorrect curl version

### ISSUE THREAD

**Issue by goaaats** [winsoft666/teemo#15]
Hello,

the vcpkg CONTROL file for teemo should be specifying `Build-Depends: curl[non-http,openssl]` instead of `Build-Depends: curl[non-http]`.

As it is, builds will fail on systems without a system-wide OpenSSL installation. The OpenSSL dependency was automatically met when cpprestsdk was still a dependency of this project, but it was since removed.

**Comment by winsoft666** [comment]
thank you, I will update as soon as possible!
