### ISSUE TITLE
报错"CREATE_TARGET_FILE_FAILED"

### ISSUE THREAD

**Issue by wongdu** [winsoft666/teemo#16]
Ubuntu 18.04.4环境引用库的时候，报错CREATE_TARGET_FILE_FAILED，
切换到root用户时候，还是报同样的错，而且也是报同样的错误
Total: 93ms

**Comment by winsoft666** [comment]
哦在Ubuntu 18.04.5 LTS环境中使用teemo_tool测试，未能重现CREATE_TARGET_FILE_FAILED错误
`./teemo_tool https://dlie.sogoucdn.com/se/sogou_explorer_8.6_1120.exe ~/test/sogou.exe 3`
