### ISSUE TITLE
希望支持代理设置

### ISSUE THREAD

**Issue by Sodacooky** [winsoft666/teemo#18]
用teemo来代替CURL时发现teemo不支持设置代理，teemo的源码也没有proxy相关内容。
我的目标是用户能根据配置文件灵活地决定用不用代理，用什么代理地址，正如CURL Easy API能做的那样。
似乎加上几个option以及在CURL中处理就能够支持。
Java的URLConnection设置Proxy的方式应该很适合teemo的风格，希望日后能支持代理设置。

**Comment by winsoft666** [comment]
感谢您的建议，后期会加入proxy设置接口



发送自我的盖乐世



-------- 原始信息 --------
发件人： Sodacooky ***@***.***>
日期: 2021/12/11 20:41 (GMT+08:00)
收件人： winsoft666/teemo ***@***.***>
抄送： Subscribed ***@***.***>
主题： [winsoft666/teemo] 希望支持代理设置 (Issue #18)


用teemo来代替CURL时发现teemo不支持设置代理，teemo的源码也没有proxy相关内容。
我的目标是用户能根据配置文件灵活地决定用不用代理，用什么代理地址，正如CURL Easy API能做的那样。
entry_handler.cpp中似乎加上几个option的处理就能够支持。
Java的URLConnection设置Proxy的方式应该很适合teemo的风格，希望日后能支持代理设置。

―

**Comment by winsoft666** [comment]
Now support setting proxy.

**Comment by winsoft666** [comment]
VCPKG port  has aslo been updated.
