### ISSUE TITLE
获取文件信息的代理设置缺失

### ISSUE THREAD

**Issue by Sodacooky** [winsoft666/teemo#19]
当调用
entry_handler.cpp: EntryHandler.requestFileInfo()
...
entry_handler.cpp: EntryHandler._asyncTaskProcess()
...
teemo.cpp: Teemo.start()
时，
其中，检测了if (!fetch_file_info_curl_)，显然第一次是nullptr，留意到fetch_file_info_curl_的类型ScopedCurl的构造函数是curl_easy_init创建一个新的CURL*，但在这个获取文件信息的操作中并没有对这个CURL*设置代理。（我上次搜索你在哪里设置proxy也是在方法里看到了你注释的那一行）。
因此下载文件产生了Result的31 FETCH_FILE_INFO_FAILED错误。

**Comment by winsoft666** [comment]
尽快修复

**Comment by winsoft666** [comment]
Fixed, but vcpkg not been updated currently.

**Comment by winsoft666** [comment]
VCPKG has updated!
