### ISSUE TITLE
Create temp file with O_TMPFILE flag

### ISSUE THREAD

**Issue by webfolderio** [winsoft666/teemo#2]
Hi,

> EnableSaveSliceToTmp: 0 or 1, optional, whether save slice file to system temp directory or not, Windows system is the path returned by GetTempPath API, Linux is /var/tmp/

You could use O_TMPFILE while creating temp file. O_TMPFILE is a Linux-specific flag for open(), that allows creation of already-unlinked temporary files, that don't need to be explicitly removed via unlink. This means that you could create a temp file without name.

https://kernelnewbies.org/Linux_3.11#head-8be09d59438b31c2a724547838f234cb33c40357

**Comment by winsoft666** [comment]
teemo has  been redesigned in architecture.
Only one tmp file in target directory at present, don't need saving to tmp directory.

**Comment by winsoft666** [comment]
teemo has  been redesigned in architecture.
Only one tmp file in target directory at present, don't need saving to tmp directory.
