### ISSUE TITLE
文件名可用性判断问题

### ISSUE THREAD

**Issue by Sodacooky** [winsoft666/teemo#20]
```
  bool includeInvalidChar = false;
  for (int i = 0; i < fullFileName.length(); i++) {
    char c = fullFileName[i];
    if (c == '\\' || c == '/' || c == ':' || c == '*' || c == '?' || c == '<' ||
        c == '>' || c == '|' || c == '"') {
      includeInvalidChar = true;
      break;
    }
  }

  if (includeInvalidChar) {
    return false;
  }
```
file_util.cpp中的这部分在commit ce2b1c2时加入。
正反斜杠出现在filename中时，应该是会被当作目录处理，在这部分改变之前我一直使用形如"directory/file.xx"的filename都是正常的。
虽然windows提示正反斜杠不能出现在文件名中，但应该能作为路径名，这样做会使带路径的文件名失效。
（我觉得如果再加一个target directory会非常累赘

**Comment by winsoft666** [comment]
按照 https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#paths 中所说的，标准的路径应该使用反斜杠进行分割。
后面考虑兼容`/`

**Comment by winsoft666** [comment]
已针对`/`做兼容性处理
