### ISSUE TITLE
下载大于4G文件文件失败

### ISSUE THREAD

**Issue by dnybz** [winsoft666/teemo#21]
你好，测试下载大于4G文件失败，提示 SLICE_DOWNLOAD_FAILED

teemo_tool_verbose.log 日志

你好，测试下载大于4G文件失败，提示 SLICE_DOWNLOAD_FAILED

teemo_tool_verbose.log 日志

[teemo] URL: http://192.168.1.2/vs2015.3.ent_chs.iso.
[teemo] Content MD5: .
[teemo] Redirect URL: .
[teemo] Thread number: 2.
[teemo] Disk Cache Size: 268435456.
[teemo] Target file path: D:\TestDown\vs2015.3.ent_chs.iso.
[teemo] Load exist slice success.
<1> [0~10485759] (10485759), Disk: 10485760, Buffer: 0
<2> [10485760~20971519] (10485759), Disk: 10485760, Buffer: 0
<3> [20971520~31457279] (10485759), Disk: 10485760, Buffer: 0
<4> [31457280~41943039] (10485759), Disk: 10485760, Buffer: 0
<5> [41943040~52428799] (10485759), Disk: 10485760, Buffer: 0
<6> [52428800~62914559] (10485759), Disk: 10485760, Buffer: 0
<7> [62914560~73400319] (10485759), Disk: 10485760, Buffer: 0
<8> [73400320~83886079] (10485759), Disk: 10485760, Buffer: 0
<9> [83886080~94371839] (10485759), Disk: 10485760, Buffer: 0
<10> [94371840~104857599] (10485759), Disk: 10485760, Buffer: 0
<11> [104857600~115343359] (10485759), Disk: 10485760, Buffer: 0
<12> [115343360~125829119] (10485759), Disk: 10485760, Buffer: 0
<13> [125829120~136314879] (10485759), Disk: 10485760, Buffer: 0
<14> [136314880~146800639] (10485759), Disk: 10485760, Buffer: 0
<15> [146800640~157286399] (10485759), Disk: 10485760, Buffer: 0
<16> [157286400~167772159] (10485759), Disk: 10485760, Buffer: 0
<17> [167772160~178257919] (10485759), Disk: 10485760, Buffer: 0
<18> [178257920~188743679] (10485759), Disk: 10485760, Buffer: 0
<19> [188743680~199229439] (10485759), Disk: 10485760, Buffer: 0
......
[teemo] CURLOPT_RANGE: -1113587514--1103101953.
[teemo] CURLOPT_RANGE: -1103101754--1092616193.
[teemo] CURLOPT_RANGE: -1092615994--1082130433.
[teemo] CURLOPT_RANGE: -1082130234--1071644673.
[teemo] CURLOPT_RANGE: -1071644474--1061158913.
[teemo] CURLOPT_RANGE: -1061158714--1050673153.
[teemo] CURLOPT_RANGE: -1050672954--1040187393.
[teemo] CURLOPT_RANGE: -1040187194--1029701633.
[teemo] CURLOPT_RANGE: -1029701434--1019215873.
[teemo] CURLOPT_RANGE: -1019215674--1008730113.
[teemo] CURLOPT_RANGE: -1008729914--998244353.
[teemo] CURLOPT_RANGE: -998244154--987758593.
[teemo] CURLOPT_RANGE: -987758394--977272833.
[teemo] CURLOPT_RANGE: -977272634--966787073.
[teemo] CURLOPT_RANGE: -966786874--956301313.
[teemo] CURLOPT_RANGE: -956301114--945815553.
[teemo] CURLOPT_RANGE: -945815354--935329793.
[teemo] CURLOPT_RANGE: -935329594--924844033.
[teemo] CURLOPT_RANGE: -924843834--914358273.
[teemo] CURLOPT_RANGE: -914358074--903872513.
[teemo] CURLOPT_RANGE: -903872314--893386753.
[teemo] CURLOPT_RANGE: -893386554--882900993.
[teemo] CURLOPT_RANGE: -882900794--872415233.
[teemo] CURLOPT_RANGE: -872415034--861929473.
[teemo] CURLOPT_RANGE: -861929274--851443713.
[teemo] CURLOPT_RANGE: -851443514--840957953.
[teemo] CURLOPT_RANGE: -840957754--830472193.
[teemo] CURLOPT_RANGE: -830471994--819986433.
[teemo] CURLOPT_RANGE: -819986234--809500673.
[teemo] CURLOPT_RESUME_FROM_LARGE: -802725888.
[teemo] Downloading end.
[teemo] Start flushing cache to disk.
[teemo] Slice total size error.

**Comment by winsoft666** [comment]
Fixed!
