### ISSUE TITLE
It doesn't recognize the file path, how can I fix it?

### ISSUE THREAD

**Issue by kwixsadz** [winsoft666/teemo#24]
I'm using local variables 

std::string Path;
std::cout << skCrypt("\n\n Enter Data File folder location : ");
std::cin >> Path;

std::shared_future<Result> async_task = efd.start(
 "url", Path, <- broken
![캡처](https://user-images.githubusercontent.com/112810585/188314542-11181b6e-9c93-45cd-8a8b-e257ca3eb627.PNG)

**Comment by winsoft666** [comment]
all of string in teemo is encoded by UTF8.

**Comment by kwixsadz** [comment]
> all of strings in teemo are encoded by UTF8.
I'm using multibyte so I converted it to utf8 and tried again, it doesn't work

**Comment by kwixsadz** [comment]
utf8 Results
[](https://cdn.discordapp.com/attachments/913081302507466822/1016947292982480916/7ab11c65032d877c.PNG)

**Comment by winsoft666** [comment]
please show me your code.

**Comment by kwixsadz** [comment]
> 

I tested two ways

string_literals , MultiByteToWideChar & WideCharToMultiByte

u8"" Result https://cdn.discordapp.com/attachments/913081302507466822/1016947292982480916/7ab11c65032d877c.PNG


multibyteToUTF8  Result https://cdn.discordapp.com/attachments/913081302507466822/1017004658394419220/2.PNG

std::string multibyteToUTF8(std::string strMulti) {

	std::string result;

	// 멀티바이트 > 유니코드
	int nLen = MultiByteToWideChar(CP_ACP, 0, &strMulti[0], int(strMulti.size()), NULL, NULL);
	std::wstring strUni(nLen, 0); //유니코드
	MultiByteToWideChar(CP_ACP, 0, &strMulti[0], int(strMulti.size()), &strUni[0], nLen);

	// 유니코드 > UTF-8
	nLen = WideCharToMultiByte(CP_UTF8, 0, strUni.c_str(), int(strUni.size()), NULL, 0, NULL, NULL);
	std::string strUTF8(nLen, 0); // UTF-8
	WideCharToMultiByte(CP_UTF8, 0, strUni.c_str(), int(strUni.size()), &strUTF8[0], nLen, NULL, NULL);
	result = strUTF8;

	return result;
}

**Comment by winsoft666** [comment]
I'm sorry, maybe I misled you.
since teemo directly output message to target:
```c++
OutputVerbose(options_->verbose_functor, u8"[teemo] Target file path: %s.\n", options_->target_file_path.c_str());
```
if terminal not support utf8, will display unreadable char.

On Win32 debug mode, teemo will also print message DbgView after conver to unicode:
```
    if (pMsgBuffer) {
#if defined(DEBUG) || defined(_DEBUG)
      OutputDebugStringW(Utf8ToUnicode(pMsgBuffer).c_str());
#endif
      if (functor) {
        functor(pMsgBuffer);
      }
    }
```

**Comment by winsoft666** [comment]
this message only for debug, not affect actual function.

**Comment by kwixsadz** [comment]
> 

Thank you for your reply, but what should I do with this?
https://cdn.discordapp.com/attachments/913081302507466822/1017017899858276352/unknown.png

**Comment by kwixsadz** [comment]
Thanks for your help.
