### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by xiaosongmao123** [winsoft666/teemo#3]
1. QueryFileSize 返回值，加上(long)消除强制转换提示
------
2. teemo.h 修改引用#include "pplx/pplxtasks.h"  ---  #include <ppltasks.h>  替换pplx:: 为concurrency::  vs2017 已经内置了ppl，不需要引用cpprest
------
3. slice_manage.cpp

 Start()方法内部修改
3.1  if (verbose_functor_) {
  std::stringstream ss_verbose; ....  如果有输出再生成日志

3.2  multi_ = curl_multi_init(); 移动到  thread_num_ = uncomplete_slice_num; 之前。应该先判断分片是否全部完成，有需要下载的再初始化multi_

3.3  if (!slice->InitCURL(multi_, each_slice_download_speed)) 这里，应该把逻辑改成可以更新url，因为有的文件下载地址是时效的,url会变动。现在的逻辑是url一变就清除上一次旧的indexfile重新开始下载。对时效url（url里面包含时间戳），不合理，不能继续下载

3.4  if (progress_functor_) {
 progress_notify_thread_ = std::async(std::launch::async, [this]() {  加上判断，有进度回调再创建进度更新的异步线程。没有回调方法，不需要创建进程

3.5  if (speed_functor_) { speed_notify_thread_  这里同样是，如果不需要回调，就不创建线程

> 3.6  if (file_size_ == -1 || (file_size_ > 0 && total_capacity == file_size_)) { if (!CombineSlice()) { 这里的逻辑应该优化

现在的逻辑是，全部分片下载完，合并文件--成功或失败

应该改成：下载完一个分片触发或者定时触发，多次执行合并，直到全部下载完执行最后一次合并--成功或失败

目的：1 遇到大文件下载(10GB)，可能用户的硬盘的空间不够用(剩余12GB)，全部下载完（分片文件占用10GB）+合并（最终文件占用10GB）会出错---【我注意到你是最后全部清理，不是合并一个分片清理一个】一边下载一边合并可以及早提示失败（下载到第5GB就提示出错退出下载，不需要下载完才出错--最后都是空间不足出错）

目的：2 一边下载一边合并可以避免下载结束时长时间合并文件--有些机械硬盘只有30MB/s的合并速度（读30MB/s+写30MB/s）10GB文件需要合并6分钟。你让用户看着下载速度==0，进度==100%，然后等待6分钟没有任何提示？

> 优化：3 这个不是重点，但可以在合并一个分片后立即清理这个分片的文件，并在indexfile里面去保存结果，这样用户只有10GB空间，可以下载10GB的文件。而不是只能下载5GB的文件（分片文件5GB+最终文件5GB==总占用10GB）

------

4. file_util.cpp GetDirectory(const utf8string& path) {
  utf8string::size_type pos = path.find_last_of(PATH_SEPARATOR);
  if (pos == utf8string::npos) return "";  判断如果路径中不包含文件夹（只给了一个文件名，下载到程序启动目录），返回“”
------
5. file_util.cpp bool CreateDirectories(const utf8string& path) {
		if (path == "") return true; 同理加上空目录直接返回不需要创建
------
6. slice.cpp static size_t DownloadWriteCallback(char* buffer, size_t size, size_t nitems, void* outstream) { 应该更改逻辑
现在的逻辑是：curl回调时直接写入文件
应该改成：创建一个buff，写入buff，buff写满刷新写入文件清空buff 以此循环（注意改这里会导致indexfile的capacity不准确（比如程序崩溃被强制退出时），任务开始（Start）时检查是否续传现在是直接读取indexfile里面的slice的capacity，需要改成读取分片文件大小更新slice的capacity）
目的：curl的回调是非常频繁的，且数据非常小。有的时候都不到几kb。创建个4MB的缓存可以极大的减少写入硬盘的次数
------
7. 这个麻烦一点，现在的逻辑是先确定线程数，然后按照线程数分片，然后按照分片数去真的下载。假设10GB文件分4线程下载，下载一段时间后暂停后重新恢复，会出现3个分片已下载完成，剩余一个分片需要下载---单线程下载这一个分片，单线程下载2.5GB。
问题1 对用户预期来讲应该是4线程去下载2.5GB。
问题2 任务第一次执行就确定了线程数，之后暂停后也不能修改--调整并发数量，如果用户暂停后重新启动任务但修改了线程数，会导致前面旧数据全部失效，需要完整的重新下载

> 应该改成：
简单讲就是线程和分片数分离。不管用户设置的是几个线程，当文件体积较大时，强制按100MB分片，10GB文件=100个分片。然后开4个（用户设置的）线程轮训按顺序下载所有分片
这样的逻辑，不管用户下载了多少，停止后恢复，都是剩余文件满线程数下载，只有最后一个分片（100MB）才会和原来一样导致单线程下载。并且用户恢复下载时可以随意的修改线程数。
最后对于大文件下载，本身就应该经常断开重连（小体积多分片），因为有的服务器会减慢长时间一直链接着的用户的下载速度，把带宽分给新用户

**Comment by winsoft666** [comment]
感谢你的建议，已列入更新计划

**Comment by winsoft666** [comment]
以上特性均已实现；
在API接口上有较大改动
