### ISSUE TITLE
Bug of two teemo client speedHandler

### ISSUE THREAD

**Issue by edigar007** [winsoft666/teemo#6]
If second filesize is smaller than first . last always is the first file size. Or am I wrong? I use teemo in a shared_ptr.
```
    if (options_ && slice_manager_) {
      int64_t now = slice_manager_->totalDownloaded();

      static int64_t last = already_download_; //here static int64
      if (now >= last) {
        int64_t downloaded = now - last;
        last = now;
        options_->speed_functor(downloaded);
      }
    }
```

**Comment by winsoft666** [comment]
a teemo handler only has one SpeedHandler.
what's the meaning of "two teemo client speedHandler"?

**Comment by edigar007** [comment]
> a teemo handler only has one SpeedHandler.
> what's the meaning of "two teemo client speedHandler"?

two teemo client download two file

**Comment by winsoft666** [comment]
Yes, you are right!
I have fixed this issue.
