### ISSUE TITLE
建议：关于硬盘文件空间分配

### ISSUE THREAD

**Issue by xiaosongmao123** [winsoft666/teemo#7]
当前方式是，下载时，先创建一个临时文件（TargetFile::createNew）
并分配全部文件体积，（CreateFixedSizeFile）

``````
Seek(f, fixed_size - 1, SEEK_SET)
fwrite("", 1, 1, f)
``````

如果要下载的文件较大（10GB）+保存在usb2.0移动硬盘里，则需要较长时间（实际上就是说的机械硬盘写入文件速度慢）

推荐修改为使用各个系统的api快速分配文件空间

mac   F_PREALLOCATE
方式一：快速预分配文件体积实际占用为0MB（毫秒级）
方式二：快速预分配文件体积实际占用文件体积（毫秒级）

linux fallocate
快速预分配文件体积实际占用文件体积（毫秒级）

windows 
NTFS分区  SetEndOfFile
快速预分配文件体积实际占用文件体积（毫秒级）

FAT32分区  没有办法，不支持快速分配

具体代码github上都有的

**最后遇到实在无法快速分配硬盘空间时**，判断文件体积是否较大，较大时不予分配文件空间，直接去下载

这样相交之前的fwrite("", 1, 1, f)，可以节省非常多的时间+减少硬盘狂转

因为fwrite("", 1, 1, f)在各个系统表现都是，使用0填充整个文件体积，就是完整的在硬盘上写入一便文件，
对于机械硬盘   10GB / 30MB/s =干等5分钟不去下载+硬盘狂转
对于固态硬盘  下载10GB文件却需要写入20GB的数据，减少了硬盘使用寿命

望及时采纳，这是有意义的

**Comment by winsoft666** [comment]
Good idea!

**Comment by winsoft666** [comment]
Fixed!
