### ISSUE TITLE
建议：关于下载进度索引文件的刷新时机

### ISSUE THREAD

**Issue by xiaosongmao123** [winsoft666/teemo#8]
看到了下载的进度索引文件

1.  .teemo  和  .efdindex  这2个临时后缀名太长了，windows要求完整的文件路径，少于256字符。这么长的临时后缀太长了，推荐修改为.td 和.ti 这种3个字符的临时后缀名

2. efdindex  里面保存有文件每个分片的下载进度
我看到只有下载成功和下载暂停2个时机，才会刷新这个文件（EntryHandler::asyncTaskProcess   finishDownloadProgress --> flushIndexFile）保存下载进度

那么就想到，下载一个10GB的文件时，分100片，下载完99片时，电脑突然自动更新重启了/蓝屏死机了/程序崩溃了/停电了 等等突发意外情况时，因为程序是直接崩溃退出的，并不会执行flushIndexFile，那么重启电脑后继续下载，则99个分片进度都会丢失，也就是需要完全重新下载，无法断点续传
  
  
  
只有下载了99片，点击暂停，此时会触发flushIndexFile，等下次继续下载时，才会读取到99片的下载进度，只下载剩余1个分片

**所以推荐**，修改为定时执行以下flushIndexFile或者在每个分片下载成功后都执行一下flushIndexFile。

最后 UNSURE_DOWNLOAD_COMPLETED这个好像没用到，删除掉吧

**Comment by xiaosongmao123** [comment]
忘了说了，efdindex 最好保存到临时文件目录，
1，看起来干净
2，避免文件残留，像百度网盘.downloading就很爱残留

**Comment by winsoft666** [comment]
Good idea!

**Comment by winsoft666** [comment]
下载进度索引文件的刷新时机已修改为定时刷新
