### ISSUE TITLE
建议：关于文件保存路径清理

### ISSUE THREAD

**Issue by xiaosongmao123** [winsoft666/teemo#9]
用这个库都是程序内api调用，
std::shared_future<Result> Teemo::start(
    const utf8string& url,
    const utf8string& target_file_path,

这里未对传入的target_file_path进行任何检查

1. windows文件路径中不允许有一些特殊字符，并且对路径长度有限制
2. 一些路径会比较奇怪比如会包含有(//)(/../)
3. linux、mac也同样不允许一些特殊字符

总之，应该检查、格式化、清理 一遍传入的target_file_path。确保无论用户传入的是什么，最大限度可以继续下载，而不是直接报错返回路径错误

**Comment by winsoft666** [comment]
Good idea!

**Comment by winsoft666** [comment]
Fixed
